modeling:
  test_size: 0.2
  target_feature_name: salary
  categorical_fature_names:
    - workclass
    - education
    - marital-status
    - occupation
    - relationship
    - race
    - sex
    - native-country
  numerical_feature_names:
    - age
    - fnlgt
    - education-num
    - capital-gain
    - capital-loss
    - hours-per-week
